### PR TITLE
Update run.sh to use RepoSense v1.8 CLI formats

### PR DESCRIPTION
**Pull request by yamidark**

### CODE REVIEW

**Comment by yamidark** [comment]
@yong24s Can help review and double-check this (and merge it if you can't, I can't seem to merge this)?

**Comment by yamidark** [comment]
@yong24s Actually the current default option for `get_reposense.py` is to use the latest release version, so it still doesn't break yet. Perhaps we can merge this in after we make the v1.8 release?

**Comment by yong24s** [comment]
@yamidark 

CS3281 dashboard using `master` 😂.

**Comment by yamidark** [comment]
>CS3281 dashboard using `master`

Noted, will update it at that side as well.

**Comment by yamidark** [comment]
@yong24s v1.8 has been merged for awhile, help to check and review this, and merge if you can.

**Pull request merged**
